# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "amdgpu" "nvme" "xhci_pci" "thunderbolt" "ahci" "usbhid" "usb_storage" "uas" "sd_mod" "pci_stub" "vfio" "vfio-pci" "vfio_iommu_type1" "virtio_net" "virtio_pci" "virtio_mmio" "virtio_blk" "virtio_scsi" "9p" "9pnet_virtio" ];
  boot.initrd.kernelModules = [ "vfio" "vfio-pci" "amdgpu" ]; 

  boot.initrd.systemd.services.rollback = {
    description = "Rollback root filesystem";
    wantedBy = [
      "initrd.target"
    ];
    after = [
      "zfs-import-zroot.service"
    ];
    before = [
      "sysroot.mount"
    ];
    path = with pkgs; [
      zfs
    ];
    unitConfig.DefaultDependencies = "no";
    serviceConfig.Type = "oneshot";
    script = ''
      zfs rollback -r zroot/encrypted/root@blank
      zfs rollback -r zroot/encrypted/home@blank
    '';
  };

  boot.supportedFilesystems = [ "zfs" ];
  boot.zfs.requestEncryptionCredentials = true; # Prompts for password input?
  services.zfs.autoScrub.enable = true;

  # fileSystems."/" =
  #   { device = "/dev/disk/by-uuid/00ef2401-13a0-4740-933c-9d6bd51c9bf4";
  #     fsType = "ext4";
  #   };

  # boot.initrd.luks.devices."luks-80a356ce-01a6-4bc3-9ed7-c84a2a694406".device = "/dev/disk/by-uuid/80a356ce-01a6-4bc3-9ed7-c84a2a694406";

  # fileSystems."/boot" =
  #   { device = "/dev/disk/by-uuid/DC3E-6165";
  #     fsType = "vfat";
  #   };

  boot.kernelModules = [ 
    "kvm-amd"
    "pci_stub"
    "vfio_pci"
    "vfio"
    "vfio_iommu_type1"
    "kvmfr"
  ];
  boot.kernelParams = [
    "iommu=pt"
    # "pcie_aspm=off"
    "amd_iommu=on"
    #"vfio-pci.ids=1002:7480,1002:ab30"
    #"pci-stub.ids=1002:7480,1002:ab30"
    "mem_sleep_default=deep"
  ];
  boot.kernelPackages = config.boot.zfs.package.latestCompatibleLinuxPackages;
  boot.extraModulePackages = [ ];

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp5s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  hardware = {
    cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    keyboard.qmk.enable = true;
    opengl = {
      driSupport = true;
      driSupport32Bit = true;
      enable = true;
      extraPackages = with pkgs; [
        amdvlk
        libva
        libvdpau
        libvdpau-va-gl
        vaapiVdpau
      ];
      extraPackages32 = [
        pkgs.driversi686Linux.amdvlk
      ];
    };
    # steam-hardware.enable = true;
  };

}
