# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "ahci" "usbhid" "usb_storage" "uas" "sd_mod" "pci_stub" "vfio" "vfio-pci" "vfio_iommu_type1" "virtio_net" "virtio_pci" "virtio_mmio" "virtio_blk" "virtio_scsi" "9p" "9pnet_virtio" ];
  boot.initrd.kernelModules = [ "vfio" "vfio-pci" ]; 

  boot.initrd.systemd.services.rollback = {
    description = "Rollback root filesystem";
    wantedBy = [
      "initrd.target"
    ];
    after = [
      "zfs-import-zroot.service"
    ];
    before = [
      "sysroot.mount"
    ];
    path = with pkgs; [
      zfs
    ];
    unitConfig.DefaultDependencies = "no";
    serviceConfig.Type = "oneshot";
    script = ''
      zfs rollback -r zroot/encrypted/root@blank
      zfs rollback -r zroot/encrypted/home@blank
    '';
  };
  # boot.initrd.postDeviceCommands = ''
  #   zfs rollback -r zroot/encrypted/root@blank
  # '';

  boot.supportedFilesystems = [ "zfs" ];
  boot.zfs.requestEncryptionCredentials = true; # Prompts for password input?
  boot.zfs.allowHibernation = false;
  services.zfs = {
    autoScrub.enable = true;
    autoScrub.pools = [ "zroot" ];
    trim.enable = true;
  };

  system.impermanence.zfs = {
    enable = true;
  };

  boot.kernelModules = [ 
    "pci_stub"
    "vfio_pci"
    "vfio"
    "vfio_iommu_type1"
    "kvmfr"
  ];
  boot.kernelParams = [
    #"iommu=pt" # Required if doing passthrough to VMs / Docker
    # "pcie_aspm=off"
    # "amd_iommu=on"
    #"vfio-pci.ids=1002:7480,1002:ab30"
    #"pci-stub.ids=1002:7480,1002:ab30"
    "mem_sleep_default=deep" # Fix for AMD-related power-draw while syspended/sleeping
  ];
  boot.kernelPackages = config.boot.zfs.package.latestCompatibleLinuxPackages;
  boot.extraModulePackages = [ ];

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp5s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = {
    system = "x86_64-linux";
  };

  hardware = {
    cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    keyboard.qmk.enable = true;
    opengl = {
      driSupport = true;
      driSupport32Bit = true;
      enable = true;
    };
  };

}
